<?php

namespace App\Services\Mobile;

use App\Models\PassengerAccount;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use RuntimeException;

class MobileOtpService
{
    public function issue(PassengerAccount $account): void
    {
        $code = $this->localCode();
        $account->forceFill([
            'otp_digest' => Hash::make($code),
            'otp_expires_at' => now()->addMinutes((int) config('mobile.otp.ttl_minutes', 10)),
        ])->save();

        Log::info('Passenger OTP generated by the local log driver.', [
            'passenger_account_id' => $account->id,
            'otp' => $code,
        ]);
    }

    public function verify(PassengerAccount $account, string $code): bool
    {
        if (!$account->otp_digest || !$account->otp_expires_at || $account->otp_expires_at->isPast()) {
            return false;
        }

        if (!Hash::check($code, $account->otp_digest)) {
            return false;
        }

        $account->forceFill([
            'mobile_verified_at' => now(),
            'otp_digest' => null,
            'otp_expires_at' => null,
        ])->save();

        return true;
    }

    public function issuePasswordReset(PassengerAccount $account): void
    {
        $code = $this->localCode();
        $account->forceFill([
            'password_reset_otp_digest' => Hash::make($code),
            'password_reset_otp_expires_at' => now()->addMinutes((int) config('mobile.otp.ttl_minutes', 10)),
            'password_reset_token_digest' => null,
            'password_reset_token_expires_at' => null,
        ])->save();

        Log::info('Passenger password reset OTP generated by the local log driver.', [
            'passenger_account_id' => $account->id,
            'otp' => $code,
        ]);
    }

    public function verifyPasswordReset(PassengerAccount $account, string $code): ?string
    {
        if (
            !$account->password_reset_otp_digest ||
            !$account->password_reset_otp_expires_at ||
            $account->password_reset_otp_expires_at->isPast() ||
            !Hash::check($code, $account->password_reset_otp_digest)
        ) {
            return null;
        }

        $token = Str::random(64);
        $account->forceFill([
            'password_reset_otp_digest' => null,
            'password_reset_otp_expires_at' => null,
            'password_reset_token_digest' => Hash::make($token),
            'password_reset_token_expires_at' => now()->addMinutes(15),
        ])->save();

        return $token;
    }

    public function resetPassword(PassengerAccount $account, string $token, string $password): bool
    {
        if (
            !$account->password_reset_token_digest ||
            !$account->password_reset_token_expires_at ||
            $account->password_reset_token_expires_at->isPast() ||
            !Hash::check($token, $account->password_reset_token_digest)
        ) {
            return false;
        }

        $account->forceFill([
            'password' => Hash::make($password),
            'password_reset_token_digest' => null,
            'password_reset_token_expires_at' => null,
        ])->save();
        $account->tokens()->delete();

        return true;
    }

    private function localCode(): string
    {
        $driver = config('mobile.otp.driver', 'disabled');
        if ($driver !== 'log' || !app()->environment(['local', 'testing'])) {
            throw new RuntimeException('Passenger OTP delivery is not configured.', 503);
        }

        return (string) random_int(100000, 999999);
    }
}
