<?php

namespace App\Services\Mobile;

use App\Models\PassengerAccount;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Http;
use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use RuntimeException;

class MobileOtpService
{
    public function issue(PassengerAccount $account): void
    {
        $this->ensureConfigured();
        $code = (string) random_int(100000, 999999);
        $account->forceFill([
            'otp_digest' => Hash::make($code),
            'otp_expires_at' => now()->addMinutes((int) config('mobile.otp.ttl_minutes', 10)),
        ])->save();

        $this->deliver($account, $code, 'signup');
    }

    public function verify(PassengerAccount $account, string $code): bool
    {
        if (!$account->otp_digest || !$account->otp_expires_at || $account->otp_expires_at->isPast()) {
            return false;
        }

        if (!Hash::check($code, $account->otp_digest)) {
            return false;
        }

        $account->forceFill([
            'mobile_verified_at' => now(),
            'otp_digest' => null,
            'otp_expires_at' => null,
        ])->save();

        return true;
    }

    public function issuePasswordReset(PassengerAccount $account): void
    {
        $this->ensureConfigured();
        $code = (string) random_int(100000, 999999);
        $account->forceFill([
            'password_reset_otp_digest' => Hash::make($code),
            'password_reset_otp_expires_at' => now()->addMinutes((int) config('mobile.otp.ttl_minutes', 10)),
            'password_reset_token_digest' => null,
            'password_reset_token_expires_at' => null,
        ])->save();

        $this->deliver($account, $code, 'password_reset');
    }

    public function verifyPasswordReset(PassengerAccount $account, string $code): ?string
    {
        if (
            !$account->password_reset_otp_digest ||
            !$account->password_reset_otp_expires_at ||
            $account->password_reset_otp_expires_at->isPast() ||
            !Hash::check($code, $account->password_reset_otp_digest)
        ) {
            return null;
        }

        $token = Str::random(64);
        $account->forceFill([
            'password_reset_otp_digest' => null,
            'password_reset_otp_expires_at' => null,
            'password_reset_token_digest' => Hash::make($token),
            'password_reset_token_expires_at' => now()->addMinutes(15),
        ])->save();

        return $token;
    }

    public function resetPassword(PassengerAccount $account, string $token, string $password): bool
    {
        if (
            !$account->password_reset_token_digest ||
            !$account->password_reset_token_expires_at ||
            $account->password_reset_token_expires_at->isPast() ||
            !Hash::check($token, $account->password_reset_token_digest)
        ) {
            return false;
        }

        $account->forceFill([
            'password' => Hash::make($password),
            'password_reset_token_digest' => null,
            'password_reset_token_expires_at' => null,
        ])->save();
        $account->tokens()->delete();

        return true;
    }

    public function ensureConfigured(): void
    {
        $driver = config('mobile.otp.driver', 'disabled');
        if ($driver === 'log' && app()->environment(['local', 'testing'])) {
            return;
        }
        if ($driver === 'whatsapp' && trim((string) config('mobile.otp.whatsapp.api_key')) !== '') {
            return;
        }
        throw new RuntimeException('Passenger OTP delivery is not configured.', 503);
    }

    private function deliver(PassengerAccount $account, string $code, string $purpose): void
    {
        if (config('mobile.otp.driver') === 'log') {
            Log::info('Passenger OTP generated by the local log driver.', [
                'passenger_account_id' => $account->id,
                'purpose' => $purpose,
                'otp' => $code,
            ]);
            return;
        }

        // Use the existing SAR Zone template contract, with mobile credentials
        // supplied by server configuration. Do not call the staff booking OTP
        // helper: its customer lookup and loyalty fields are unrelated to signup.
        try {
            $response = Http::withToken(config('mobile.otp.whatsapp.api_key'))
                ->acceptJson()
                ->withOptions(['allow_redirects' => false])
                ->timeout(10)
                ->post('https://wa.sarzone.com/api/v1/whatsapp/send-template', [
                    'client_code' => config('mobile.otp.whatsapp.client_code', 'kainat-travels'),
                    'to' => $this->whatsappNumber($account->mobile),
                    'template_name' => config('mobile.otp.whatsapp.template', 'otp'),
                    'language_code' => config('mobile.otp.whatsapp.language', 'en'),
                    'variables' => ['code' => $code],
                    'reference_id' => 'KAINAT_MOBILE_' . $purpose . '_' . $account->id . '_' . Str::uuid(),
                ]);
            if ($response->successful() && $response->json('success') === true) {
                return;
            }
            // Provider response bodies may contain credentials or personal data.
            Log::warning('Mobile WhatsApp OTP delivery rejected.', [
                'passenger_account_id' => $account->id,
                'purpose' => $purpose,
                'status' => $response->status(),
            ]);
        } catch (ConnectionException $exception) {
            Log::warning('Mobile WhatsApp OTP connection failed.', [
                'passenger_account_id' => $account->id,
                'purpose' => $purpose,
            ]);
        }

        throw new RuntimeException('Could not send the WhatsApp code. Please try again shortly.', 503);
    }

    private function whatsappNumber(string $number): string
    {
        $number = preg_replace('/\D+/', '', $number);
        if (preg_match('/^03[0-9]{9}$/', $number)) {
            return '92' . substr($number, 1);
        }
        if (preg_match('/^3[0-9]{9}$/', $number)) {
            return '92' . $number;
        }
        if (preg_match('/^923[0-9]{9}$/', $number)) {
            return $number;
        }
        throw new RuntimeException('Enter a valid Pakistani WhatsApp mobile number.', 422);
    }
}
